# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Point.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Point(object):
    def setupUi(self, Point):
        Point.setObjectName("Point")
        Point.resize(227, 268)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Point)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Point)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.idP = QtWidgets.QLabel(Point)
        self.idP.setObjectName("idP")
        self.horizontalLayout.addWidget(self.idP)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Address = QtWidgets.QLabel(Point)
        self.Address.setObjectName("Address")
        self.horizontalLayout_2.addWidget(self.Address)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineAddress = QtWidgets.QLineEdit(Point)
        self.lineAddress.setObjectName("lineAddress")
        self.horizontalLayout_2.addWidget(self.lineAddress)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Point)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Point)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Product = QtWidgets.QLabel(Point)
        self.Product.setObjectName("Product")
        self.horizontalLayout_4.addWidget(self.Product)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.comboBox = QtWidgets.QComboBox(Point)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton = QtWidgets.QPushButton(Point)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Point)
        QtCore.QMetaObject.connectSlotsByName(Point)

    def retranslateUi(self, Point):
        _translate = QtCore.QCoreApplication.translate
        Point.setWindowTitle(_translate("Point", "Dialog"))
        self.label.setText(_translate("Point", "Изменение точки"))
        self.idP.setText(_translate("Point", "id"))
        self.Address.setText(_translate("Point", "Адрес"))
        self.label_4.setText(_translate("Point", "Доход"))
        self.Product.setText(_translate("Point", "Товар"))
        self.pushButton.setText(_translate("Point", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Point = QtWidgets.QDialog()
    ui = Ui_Point()
    ui.setupUi(Point)
    Point.show()
    sys.exit(app.exec_())
