from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(702, 379)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineProduct = QtWidgets.QLineEdit(Form)
        self.lineProduct.setObjectName("lineProduct")
        self.horizontalLayout_12.addWidget(self.lineProduct)
        self.SearchProduct = QtWidgets.QPushButton(Form)
        self.SearchProduct.setObjectName("SearchProduct")
        self.horizontalLayout_12.addWidget(self.SearchProduct)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tableProduct = QtWidgets.QTableWidget(Form)
        self.tableProduct.setObjectName("tableProduct")
        self.tableProduct.setColumnCount(4)
        self.tableProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_10.addWidget(self.tableProduct)
        self.verticalScrollBar_4 = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_4.setObjectName("verticalScrollBar_4")
        self.horizontalLayout_10.addWidget(self.verticalScrollBar_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.ProductUpdate = QtWidgets.QPushButton(Form)
        self.ProductUpdate.setObjectName("ProductUpdate")
        self.verticalLayout_5.addWidget(self.ProductUpdate)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.AddProduct = QtWidgets.QPushButton(Form)
        self.AddProduct.setObjectName("AddProduct")
        self.horizontalLayout_11.addWidget(self.AddProduct)
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.DeleteProduct = QtWidgets.QPushButton(Form)
        self.DeleteProduct.setObjectName("DeleteProduct")
        self.horizontalLayout_11.addWidget(self.DeleteProduct)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout_5)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SearchProduct.setText(_translate("Form", "Поиск"))
        item = self.tableProduct.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.tableProduct.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Название"))
        item = self.tableProduct.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Цена"))
        item = self.tableProduct.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Количество"))
        self.ProductUpdate.setText(_translate("Form", "Обновить данные"))
        self.AddProduct.setText(_translate("Form", "Добавить"))
        self.DeleteProduct.setText(_translate("Form", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
