from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(758, 379)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.linePoint = QtWidgets.QLineEdit(Form)
        self.linePoint.setObjectName("linePoint")
        self.horizontalLayout_16.addWidget(self.linePoint)
        self.SearchPoint = QtWidgets.QPushButton(Form)
        self.SearchPoint.setObjectName("SearchPoint")
        self.horizontalLayout_16.addWidget(self.SearchPoint)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.TablePoint = QtWidgets.QTableWidget(Form)
        #self.TablePoint.setEnabled(True)   #
        self.TablePoint.setObjectName("TablePoint")
        self.TablePoint.setColumnCount(5)
        self.TablePoint.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_7.addWidget(self.TablePoint)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.horizontalLayout_7.addWidget(self.verticalScrollBar_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.PointUpdate = QtWidgets.QPushButton(Form)
        self.PointUpdate.setObjectName("PointUpdate")
        self.verticalLayout_8.addWidget(self.PointUpdate)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.AddPoint = QtWidgets.QPushButton(Form)
        self.AddPoint.setObjectName("AddPoint")
        self.horizontalLayout_20.addWidget(self.AddPoint)
        self.ChangePoint = QtWidgets.QPushButton(Form)
        self.ChangePoint.setObjectName("ChangePoint")
        self.horizontalLayout_20.addWidget(self.ChangePoint)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        spacerItem = QtWidgets.QSpacerItem(238, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.DeletePoint = QtWidgets.QPushButton(Form)
        self.DeletePoint.setObjectName("DeletePoint")
        self.horizontalLayout_17.addWidget(self.DeletePoint)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout.addLayout(self.verticalLayout_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SearchPoint.setText(_translate("Form", "Поиск"))
        item = self.TablePoint.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.TablePoint.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Адрес"))
        item = self.TablePoint.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Доход"))
        item = self.TablePoint.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Товар"))
        #item = self.TablePoint.horizontalHeaderItem(4)
        #item.setText(_translate("Form", "Количество работников "))
        self.PointUpdate.setText(_translate("Form", "Обновить данные"))
        self.AddPoint.setText(_translate("Form", "Добавить"))
        self.ChangePoint.setText(_translate("Form", "Изменить"))
        self.DeletePoint.setText(_translate("Form", "Удалить"))
