# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Shop_ProductTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 399)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineShopProduct = QtWidgets.QLineEdit(Form)
        self.lineShopProduct.setObjectName("lineShopProduct")
        self.horizontalLayout_16.addWidget(self.lineShopProduct)
        self.SearchShopProduct = QtWidgets.QPushButton(Form)
        self.SearchShopProduct.setObjectName("SearchShopProduct")
        self.horizontalLayout_16.addWidget(self.SearchShopProduct)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableShopProduct = QtWidgets.QTableWidget(Form)
        self.tableShopProduct.setEnabled(True)
        self.tableShopProduct.setObjectName("tableShopProduct")
        self.tableShopProduct.setColumnCount(2)
        self.tableShopProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableShopProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableShopProduct.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_7.addWidget(self.tableShopProduct)
        self.verticalScrollBar = QtWidgets.QScrollBar(Form)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_7.addWidget(self.verticalScrollBar)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.ShopProductUpdate = QtWidgets.QPushButton(Form)
        self.ShopProductUpdate.setObjectName("ShopProductUpdate")
        self.verticalLayout_8.addWidget(self.ShopProductUpdate)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.AddShopProduct = QtWidgets.QPushButton(Form)
        self.AddShopProduct.setObjectName("AddShopProduct")
        self.horizontalLayout_20.addWidget(self.AddShopProduct)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        spacerItem = QtWidgets.QSpacerItem(238, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.DeleteShopProduct = QtWidgets.QPushButton(Form)
        self.DeleteShopProduct.setObjectName("DeleteShopProduct")
        self.horizontalLayout_17.addWidget(self.DeleteShopProduct)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout.addLayout(self.verticalLayout_8)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SearchShopProduct.setText(_translate("Form", "Поиск"))
        item = self.tableShopProduct.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id магазина"))
        item = self.tableShopProduct.horizontalHeaderItem(1)
        item.setText(_translate("Form", "id продукта"))
        self.ShopProductUpdate.setText(_translate("Form", "Обновить данные"))
        self.AddShopProduct.setText(_translate("Form", "Добавить"))
        self.DeleteShopProduct.setText(_translate("Form", "Удалить"))
