# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShopWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createShop(object):
    def setupUi(self, createShop):
        createShop.setObjectName("createShop")
        createShop.resize(224, 218)
        self.horizontalLayout = QtWidgets.QHBoxLayout(createShop)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.WindowCShop = QtWidgets.QVBoxLayout()
        self.WindowCShop.setObjectName("WindowCShop")
        self.Window2CShop = QtWidgets.QVBoxLayout()
        self.Window2CShop.setObjectName("Window2CShop")
        self.LabelCShop = QtWidgets.QVBoxLayout()
        self.LabelCShop.setObjectName("LabelCShop")
        self.labelShop = QtWidgets.QLabel(createShop)
        self.labelShop.setObjectName("labelShop")
        self.LabelCShop.addWidget(self.labelShop)
        self.id_Shop = QtWidgets.QLabel(createShop)
        self.id_Shop.setObjectName("id_Shop")
        self.LabelCShop.addWidget(self.id_Shop)
        self.Window2CShop.addLayout(self.LabelCShop)
        self.ShopAdd = QtWidgets.QHBoxLayout()
        self.ShopAdd.setObjectName("ShopAdd")
        self.labelAddShop = QtWidgets.QLabel(createShop)
        self.labelAddShop.setObjectName("labelAddShop")
        self.ShopAdd.addWidget(self.labelAddShop)
        self.lineAddShop = QtWidgets.QLineEdit(createShop)
        self.lineAddShop.setObjectName("lineAddShop")
        self.ShopAdd.addWidget(self.lineAddShop)
        self.Window2CShop.addLayout(self.ShopAdd)
        self.ShopIncome = QtWidgets.QHBoxLayout()
        self.ShopIncome.setObjectName("ShopIncome")
        self.labelShopIncome = QtWidgets.QLabel(createShop)
        self.labelShopIncome.setObjectName("labelShopIncome")
        self.ShopIncome.addWidget(self.labelShopIncome)
        self.ShopIncome_2 = QtWidgets.QLineEdit(createShop)
        self.ShopIncome_2.setObjectName("ShopIncome_2")
        self.ShopIncome.addWidget(self.ShopIncome_2)
        self.Window2CShop.addLayout(self.ShopIncome)
        self.WindowCShop.addLayout(self.Window2CShop)
        self.pushButton = QtWidgets.QPushButton(createShop)
        self.pushButton.setObjectName("pushButton")
        self.WindowCShop.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.WindowCShop)

        self.retranslateUi(createShop)
        QtCore.QMetaObject.connectSlotsByName(createShop)

    def retranslateUi(self, createShop):
        _translate = QtCore.QCoreApplication.translate
        createShop.setWindowTitle(_translate("createShop", "Dialog"))
        self.labelShop.setText(_translate("createShop", "Изменение магазина"))
        self.id_Shop.setText(_translate("createShop", "id"))
        self.labelAddShop.setText(_translate("createShop", "Адрес"))
        self.labelShopIncome.setText(_translate("createShop", "Доход"))
        self.pushButton.setText(_translate("createShop", "Сохранить"))
