from PyQt5 import QtCore, QtGui, QtWidgets

from shop_tab import ShopTab
from worker_tab import WorkerTab


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWiget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tabWiget.setFont(font)
        self.tabWiget.setObjectName("tabWiget")
        self.worker = WorkerTab()
        self.worker.setObjectName("worker")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.worker)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.tabWiget.addTab(self.worker, "")
        self.point = ShopTab() #QtWidgets.QWidget()
        self.point.setObjectName("point")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.point)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWiget.addTab(self.point, "")
        self.Storage = QtWidgets.QWidget()
        self.Storage.setObjectName("Storage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Storage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineStorage = QtWidgets.QLineEdit(self.Storage)
        self.lineStorage.setObjectName("lineStorage")
        self.horizontalLayout_8.addWidget(self.lineStorage)
        self.SearchStorage = QtWidgets.QPushButton(self.Storage)
        self.SearchStorage.setObjectName("SearchStorage")
        self.horizontalLayout_8.addWidget(self.SearchStorage)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.Storage)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_9.addWidget(self.tableWidget_3)
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(self.Storage)
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.horizontalLayout_9.addWidget(self.verticalScrollBar_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.StorageUpdate = QtWidgets.QPushButton(self.Storage)
        self.StorageUpdate.setObjectName("StorageUpdate")
        self.verticalLayout_4.addWidget(self.StorageUpdate)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.tabWiget.addTab(self.Storage, "")
        self.Client = QtWidgets.QWidget()
        self.Client.setObjectName("Client")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Client)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineClient = QtWidgets.QLineEdit(self.Client)
        self.lineClient.setObjectName("lineClient")
        self.horizontalLayout_13.addWidget(self.lineClient)
        self.SearchClient = QtWidgets.QPushButton(self.Client)
        self.SearchClient.setObjectName("SearchClient")
        self.horizontalLayout_13.addWidget(self.SearchClient)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tableClient = QtWidgets.QTableWidget(self.Client)
        self.tableClient.setObjectName("tableClient")
        self.tableClient.setColumnCount(3)
        self.tableClient.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableClient.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClient.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClient.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_14.addWidget(self.tableClient)
        self.verticalScrollBar_5 = QtWidgets.QScrollBar(self.Client)
        self.verticalScrollBar_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_5.setObjectName("verticalScrollBar_5")
        self.horizontalLayout_14.addWidget(self.verticalScrollBar_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.ClientUpdate = QtWidgets.QPushButton(self.Client)
        self.ClientUpdate.setObjectName("ClientUpdate")
        self.verticalLayout_6.addWidget(self.ClientUpdate)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.AddClient = QtWidgets.QPushButton(self.Client)
        self.AddClient.setObjectName("AddClient")
        self.horizontalLayout_15.addWidget(self.AddClient)
        self.ChangeClient = QtWidgets.QPushButton(self.Client)
        self.ChangeClient.setObjectName("ChangeClient")
        self.horizontalLayout_15.addWidget(self.ChangeClient)
        spacerItem = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem)
        self.DeleteClient = QtWidgets.QPushButton(self.Client)
        self.DeleteClient.setObjectName("DeleteClient")
        self.horizontalLayout_15.addWidget(self.DeleteClient)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.verticalLayout_11.addLayout(self.verticalLayout_6)
        self.tabWiget.addTab(self.Client, "")
        self.Product = QtWidgets.QWidget()
        self.Product.setObjectName("Product")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Product)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWiget.addTab(self.Product, "")
        self.verticalLayout.addWidget(self.tabWiget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWiget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.worker), _translate("MainWindow", "Работник"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.point), _translate("MainWindow", "Точка"))
        self.SearchStorage.setText(_translate("MainWindow", "Поиск"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название товара "))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Количество на складе"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Поставщик"))
        self.StorageUpdate.setText(_translate("MainWindow", "Обновить данные"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.Storage), _translate("MainWindow", "Склад"))
        self.SearchClient.setText(_translate("MainWindow", "Поиск"))
        item = self.tableClient.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableClient.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.tableClient.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Телефон"))
        self.ClientUpdate.setText(_translate("MainWindow", "Обновить данные"))
        self.AddClient.setText(_translate("MainWindow", "Добавить"))
        self.ChangeClient.setText(_translate("MainWindow", "Изменить"))
        self.DeleteClient.setText(_translate("MainWindow", "Удалить"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.Client), _translate("MainWindow", "Клиент"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.Product), _translate("MainWindow", "Товар"))
