from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(814, 521)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWiget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tabWiget.setFont(font)
        self.tabWiget.setObjectName("tabWiget")
        self.worker = QtWidgets.QWidget()
        self.worker.setObjectName("worker")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.worker)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.WorkerLine = QtWidgets.QLineEdit(self.worker)
        self.WorkerLine.setObjectName("WorkerLine")
        self.horizontalLayout.addWidget(self.WorkerLine)
        self.SearchWorker = QtWidgets.QPushButton(self.worker)
        self.SearchWorker.setObjectName("SearchWorker")
        self.horizontalLayout.addWidget(self.SearchWorker)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWorker = QtWidgets.QTableWidget(self.worker)
        self.tableWorker.setObjectName("tableWorker")
        self.tableWorker.setColumnCount(7)
        self.tableWorker.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorker.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorker.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorker.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorker.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorker.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorker.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWorker.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_6.addWidget(self.tableWorker)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.worker)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_6.addWidget(self.verticalScrollBar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.WorkerUpdate = QtWidgets.QPushButton(self.worker)
        self.WorkerUpdate.setObjectName("WorkerUpdate")
        self.verticalLayout_2.addWidget(self.WorkerUpdate)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.AddWorker = QtWidgets.QPushButton(self.worker)
        self.AddWorker.setObjectName("AddWorker")
        self.horizontalLayout_2.addWidget(self.AddWorker)
        self.ChangeWorker = QtWidgets.QPushButton(self.worker)
        self.ChangeWorker.setObjectName("ChangeWorker")
        self.horizontalLayout_2.addWidget(self.ChangeWorker)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(238, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.DeleteWorker = QtWidgets.QPushButton(self.worker)
        self.DeleteWorker.setObjectName("DeleteWorker")
        self.horizontalLayout_5.addWidget(self.DeleteWorker)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_21.addLayout(self.verticalLayout_2)
        self.tabWiget.addTab(self.worker, "")
        self.point = QtWidgets.QWidget()
        self.point.setObjectName("point")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.point)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.linePoint = QtWidgets.QLineEdit(self.point)
        self.linePoint.setObjectName("linePoint")
        self.horizontalLayout_16.addWidget(self.linePoint)
        self.SearchPoint = QtWidgets.QPushButton(self.point)
        self.SearchPoint.setObjectName("SearchPoint")
        self.horizontalLayout_16.addWidget(self.SearchPoint)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.TablePoint = QtWidgets.QTableWidget(self.point)
        self.TablePoint.setObjectName("TablePoint")
        self.TablePoint.setColumnCount(5)
        self.TablePoint.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablePoint.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_7.addWidget(self.TablePoint)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.point)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.horizontalLayout_7.addWidget(self.verticalScrollBar_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.PointUpdate = QtWidgets.QPushButton(self.point)
        self.PointUpdate.setObjectName("PointUpdate")
        self.verticalLayout_8.addWidget(self.PointUpdate)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.AddPoint = QtWidgets.QPushButton(self.point)
        self.AddPoint.setObjectName("AddPoint")
        self.horizontalLayout_20.addWidget(self.AddPoint)
        self.ChangePoint = QtWidgets.QPushButton(self.point)
        self.ChangePoint.setObjectName("ChangePoint")
        self.horizontalLayout_20.addWidget(self.ChangePoint)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        spacerItem1 = QtWidgets.QSpacerItem(238, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_18)
        self.DeletePoint = QtWidgets.QPushButton(self.point)
        self.DeletePoint.setObjectName("DeletePoint")
        self.horizontalLayout_17.addWidget(self.DeletePoint)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.tabWiget.addTab(self.point, "")
        self.Storage = QtWidgets.QWidget()
        self.Storage.setObjectName("Storage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Storage)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineStorage = QtWidgets.QLineEdit(self.Storage)
        self.lineStorage.setObjectName("lineStorage")
        self.horizontalLayout_8.addWidget(self.lineStorage)
        self.SearchStorage = QtWidgets.QPushButton(self.Storage)
        self.SearchStorage.setObjectName("SearchStorage")
        self.horizontalLayout_8.addWidget(self.SearchStorage)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.Storage)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.horizontalLayout_9.addWidget(self.tableWidget_3)
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(self.Storage)
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.horizontalLayout_9.addWidget(self.verticalScrollBar_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.StorageUpdate = QtWidgets.QPushButton(self.Storage)
        self.StorageUpdate.setObjectName("StorageUpdate")
        self.verticalLayout_4.addWidget(self.StorageUpdate)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.tabWiget.addTab(self.Storage, "")
        self.Client = QtWidgets.QWidget()
        self.Client.setObjectName("Client")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Client)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lineClient = QtWidgets.QLineEdit(self.Client)
        self.lineClient.setObjectName("lineClient")
        self.horizontalLayout_13.addWidget(self.lineClient)
        self.SearchClient = QtWidgets.QPushButton(self.Client)
        self.SearchClient.setObjectName("SearchClient")
        self.horizontalLayout_13.addWidget(self.SearchClient)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.tableClient = QtWidgets.QTableWidget(self.Client)
        self.tableClient.setObjectName("tableClient")
        self.tableClient.setColumnCount(3)
        self.tableClient.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableClient.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClient.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableClient.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_14.addWidget(self.tableClient)
        self.verticalScrollBar_5 = QtWidgets.QScrollBar(self.Client)
        self.verticalScrollBar_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_5.setObjectName("verticalScrollBar_5")
        self.horizontalLayout_14.addWidget(self.verticalScrollBar_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.ClientUpdate = QtWidgets.QPushButton(self.Client)
        self.ClientUpdate.setObjectName("ClientUpdate")
        self.verticalLayout_6.addWidget(self.ClientUpdate)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.AddClient = QtWidgets.QPushButton(self.Client)
        self.AddClient.setObjectName("AddClient")
        self.horizontalLayout_15.addWidget(self.AddClient)
        self.ChangeClient = QtWidgets.QPushButton(self.Client)
        self.ChangeClient.setObjectName("ChangeClient")
        self.horizontalLayout_15.addWidget(self.ChangeClient)
        spacerItem2 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.DeleteClient = QtWidgets.QPushButton(self.Client)
        self.DeleteClient.setObjectName("DeleteClient")
        self.horizontalLayout_15.addWidget(self.DeleteClient)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.verticalLayout_11.addLayout(self.verticalLayout_6)
        self.tabWiget.addTab(self.Client, "")
        self.Product = QtWidgets.QWidget()
        self.Product.setObjectName("Product")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Product)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineProduct = QtWidgets.QLineEdit(self.Product)
        self.lineProduct.setObjectName("lineProduct")
        self.horizontalLayout_12.addWidget(self.lineProduct)
        self.SearchProduct = QtWidgets.QPushButton(self.Product)
        self.SearchProduct.setObjectName("SearchProduct")
        self.horizontalLayout_12.addWidget(self.SearchProduct)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.tableProduct = QtWidgets.QTableWidget(self.Product)
        self.tableProduct.setObjectName("tableProduct")
        self.tableProduct.setColumnCount(4)
        self.tableProduct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProduct.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_10.addWidget(self.tableProduct)
        self.verticalScrollBar_4 = QtWidgets.QScrollBar(self.Product)
        self.verticalScrollBar_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_4.setObjectName("verticalScrollBar_4")
        self.horizontalLayout_10.addWidget(self.verticalScrollBar_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.ProductUpdate = QtWidgets.QPushButton(self.Product)
        self.ProductUpdate.setObjectName("ProductUpdate")
        self.verticalLayout_5.addWidget(self.ProductUpdate)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.AddProduct = QtWidgets.QPushButton(self.Product)
        self.AddProduct.setObjectName("AddProduct")
        self.horizontalLayout_11.addWidget(self.AddProduct)
        self.ChangeProduct = QtWidgets.QPushButton(self.Product)
        self.ChangeProduct.setObjectName("ChangeProduct")
        self.horizontalLayout_11.addWidget(self.ChangeProduct)
        spacerItem3 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.DeleteProduct = QtWidgets.QPushButton(self.Product)
        self.DeleteProduct.setObjectName("DeleteProduct")
        self.horizontalLayout_11.addWidget(self.DeleteProduct)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        self.tabWiget.addTab(self.Product, "")
        self.verticalLayout.addWidget(self.tabWiget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 814, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWiget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchWorker.setText(_translate("MainWindow", "Поиск"))
        item = self.tableWorker.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWorker.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.tableWorker.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Должность"))
        item = self.tableWorker.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Телефон"))
        item = self.tableWorker.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Зарплата"))
        item = self.tableWorker.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Пасспорт"))
        item = self.tableWorker.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Адрес"))
        self.WorkerUpdate.setText(_translate("MainWindow", "Обновить данные"))
        self.AddWorker.setText(_translate("MainWindow", "Добавить"))
        self.ChangeWorker.setText(_translate("MainWindow", "Изменить"))
        self.DeleteWorker.setText(_translate("MainWindow", "Удалить"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.worker), _translate("MainWindow", "Работник"))
        self.SearchPoint.setText(_translate("MainWindow", "Поиск"))
        item = self.TablePoint.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.TablePoint.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Адрес"))
        item = self.TablePoint.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Доход"))
        item = self.TablePoint.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Товар"))
        item = self.TablePoint.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Количество работников "))
        self.PointUpdate.setText(_translate("MainWindow", "Обновить данные"))
        self.AddPoint.setText(_translate("MainWindow", "Добавить"))
        self.ChangePoint.setText(_translate("MainWindow", "Изменить"))
        self.DeletePoint.setText(_translate("MainWindow", "Удалить"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.point), _translate("MainWindow", "Точка"))
        self.SearchStorage.setText(_translate("MainWindow", "Поиск"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название товара "))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Количество на складе"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Поставщик"))
        self.StorageUpdate.setText(_translate("MainWindow", "Обновить данные"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.Storage), _translate("MainWindow", "Склад"))
        self.SearchClient.setText(_translate("MainWindow", "Поиск"))
        item = self.tableClient.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableClient.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.tableClient.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Телефон"))
        self.ClientUpdate.setText(_translate("MainWindow", "Обновить данные"))
        self.AddClient.setText(_translate("MainWindow", "Добавить"))
        self.ChangeClient.setText(_translate("MainWindow", "Изменить"))
        self.DeleteClient.setText(_translate("MainWindow", "Удалить"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.Client), _translate("MainWindow", "Клиент"))
        self.SearchProduct.setText(_translate("MainWindow", "Поиск"))
        item = self.tableProduct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableProduct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableProduct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Цена"))
        item = self.tableProduct.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Количество"))
        self.ProductUpdate.setText(_translate("MainWindow", "Обновить данные"))
        self.AddProduct.setText(_translate("MainWindow", "Добавить"))
        self.ChangeProduct.setText(_translate("MainWindow", "Изменить"))
        self.DeleteProduct.setText(_translate("MainWindow", "Удалить"))
        self.tabWiget.setTabText(self.tabWiget.indexOf(self.Product), _translate("MainWindow", "Товар"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
